/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.management.system;


import java.sql.*;
import java.util.Calendar;
import java.util.Date;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.text.SimpleDateFormat;


/**
 *
 * @author pasin
 */
public class UserMain extends javax.swing.JFrame {

  

    /**
     * Creates new form UserMain
     */
    public UserMain() {
        initComponents();
  
        
    }   



                

                    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        mainPanel = new javax.swing.JTabbedPane();
        statusPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        busno = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        jSpinner1 = new javax.swing.JSpinner(sm);
        Date date1 = new Date();
        SpinnerDateModel sm1 =
        new SpinnerDateModel(date1,null,null,Calendar.HOUR_OF_DAY);
        jSpinner2 = new javax.swing.JSpinner(sm1);
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        bookingMainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        bookingPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        booking_from = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        booking_to = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        booking_busno = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        booking_time = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        booking_passenger = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        passengerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        passenger_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passenger_dob = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        passenger_male = new javax.swing.JRadioButton();
        passenger_female = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        passenger_phoneno = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 610));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(3306, 600));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage (1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("         Welcome!!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 2, 810, 160));

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (1).png"))); // NOI18N
        jLabel6.setToolTipText("");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 38));

        jButton12.setBackground(new java.awt.Color(255, 153, 204));
        jButton12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 51, 204));
        jButton12.setText("Home");
        jButton12.setToolTipText("");
        jButton12.setBorderPainted(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 120, 30));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jPanel11.setBackground(new java.awt.Color(204, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/booking (1).png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 38));

        jButton13.setBackground(new java.awt.Color(255, 153, 204));
        jButton13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 204));
        jButton13.setText("Booking");
        jButton13.setBorderPainted(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 120, 30));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 40));

        jPanel12.setBackground(new java.awt.Color(204, 153, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-file.png"))); // NOI18N
        jLabel8.setToolTipText("");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 38));

        jButton14.setBackground(new java.awt.Color(255, 153, 204));
        jButton14.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 204));
        jButton14.setText("Search");
        jButton14.setBorderPainted(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 120, 30));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        jPanel9.setBackground(new java.awt.Color(204, 153, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jLabel12.setToolTipText("");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 38));

        jButton16.setBackground(new java.awt.Color(255, 153, 204));
        jButton16.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 204));
        jButton16.setText("Exit");
        jButton16.setBorderPainted(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 120, 30));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        mainPanel.setBackground(new java.awt.Color(255, 255, 204));

        statusPanel.setBackground(new java.awt.Color(255, 255, 204));
        statusPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Date: ");
        jLabel18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        statusPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 30));

        jDateChooser1.setBackground(new java.awt.Color(51, 51, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        statusPanel.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Bus No :");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        statusPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 30));

        busno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busnoActionPerformed(evt);
            }
        });
        statusPanel.add(busno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Arrive At :");
        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        statusPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Left At :");
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        statusPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1,"HH:mm:ss");
        jSpinner1.setEditor(de);
        statusPanel.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, 30));

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(jSpinner2,"HH:mm:ss");
        jSpinner2.setEditor(de1);
        statusPanel.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 30));

        jButton17.setText("Submit");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        statusPanel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, 40));

        jButton18.setText("Clear");
        jButton18.setActionCommand("");
        statusPanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N
        statusPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));

        mainPanel.addTab("tab1", statusPanel);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 255, 204), null, null));
        jPanel4.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background-check.png"))); // NOI18N
        jButton2.setText("Passenger");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(12, 74, 140, 39);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reservation.png"))); // NOI18N
        jButton3.setText("Booking");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(12, 135, 140, 37);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N
        jPanel4.add(jLabel19);
        jLabel19.setBounds(0, 0, 800, 390);

        javax.swing.GroupLayout bookingMainPanelLayout = new javax.swing.GroupLayout(bookingMainPanel);
        bookingMainPanel.setLayout(bookingMainPanelLayout);
        bookingMainPanelLayout.setHorizontalGroup(
            bookingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookingMainPanelLayout.setVerticalGroup(
            bookingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.addTab("tab2", bookingMainPanel);

        bookingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Booking from       :");
        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bookingPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 30));

        booking_from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kegalle" }));
        bookingPanel.add(booking_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Booking to           :");
        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bookingPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 30));

        booking_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking_toActionPerformed(evt);
            }
        });
        bookingPanel.add(booking_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 160, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Date                    :");
        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bookingPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 30));

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        bookingPanel.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 30));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("Bus No                :");
        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bookingPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 30));

        bookingPanel.add(booking_busno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 30));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("Time                   : ");
        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bookingPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        bookingPanel.add(booking_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("Passenger name   :");
        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bookingPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 30));

        bookingPanel.add(booking_passenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, 30));

        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        bookingPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 40));

        jButton10.setText("Clear");
        bookingPanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N
        bookingPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));

        mainPanel.addTab("tab8", bookingPanel);

        passengerPanel.setBackground(new java.awt.Color(153, 255, 153));
        passengerPanel.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(51, 0, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Name                  : ");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        passengerPanel.add(jLabel5);
        jLabel5.setBounds(10, 30, 150, 30);

        passenger_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_nameActionPerformed(evt);
            }
        });
        passengerPanel.add(passenger_name);
        passenger_name.setBounds(190, 30, 270, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Date of Birth        :");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        passengerPanel.add(jLabel9);
        jLabel9.setBounds(10, 70, 150, 30);

        passenger_dob.setDateFormatString("yyyy-MM-dd");
        passengerPanel.add(passenger_dob);
        passenger_dob.setBounds(190, 70, 190, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Gender                :");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        passengerPanel.add(jLabel11);
        jLabel11.setBounds(10, 110, 150, 30);

        buttonGroup1.add(passenger_male);
        passenger_male.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passenger_male.setText("Male");
        passengerPanel.add(passenger_male);
        passenger_male.setBounds(190, 110, 80, 30);

        buttonGroup1.add(passenger_female);
        passenger_female.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passenger_female.setText("Female");
        passengerPanel.add(passenger_female);
        passenger_female.setBounds(300, 110, 80, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Telephone No      :");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        passengerPanel.add(jLabel10);
        jLabel10.setBounds(10, 150, 150, 30);

        passenger_phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passenger_phonenoActionPerformed(evt);
            }
        });
        passengerPanel.add(passenger_phoneno);
        passenger_phoneno.setBounds(190, 150, 270, 30);

        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        passengerPanel.add(jButton6);
        jButton6.setBounds(10, 200, 90, 40);

        jButton15.setText("Clear");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        passengerPanel.add(jButton15);
        jButton15.setBounds(140, 200, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        passengerPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 390);

        mainPanel.addTab("tab8", passengerPanel);

        searchPanel.setBackground(new java.awt.Color(255, 255, 204));
        searchPanel.setLayout(null);

        jButton8.setBackground(new java.awt.Color(255, 204, 204));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus.png"))); // NOI18N
        jButton8.setText("Bus");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton8);
        jButton8.setBounds(10, 21, 163, 35);

        jButton7.setBackground(new java.awt.Color(255, 204, 153));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/route.png"))); // NOI18N
        jButton7.setText("Route");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton7);
        jButton7.setBounds(10, 74, 163, 41);

        jButton4.setBackground(new java.awt.Color(255, 204, 102));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passenger (1).png"))); // NOI18N
        jButton4.setText("Passenger");
        jButton4.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton4);
        jButton4.setBounds(10, 139, 163, 39);

        jButton5.setBackground(new java.awt.Color(255, 153, 51));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online-booking.png"))); // NOI18N
        jButton5.setText("Booking");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton5);
        jButton5.setBounds(10, 196, 163, 37);

        jButton11.setBackground(new java.awt.Color(255, 102, 51));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(102, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact-list.png"))); // NOI18N
        jButton11.setText("User");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton11);
        jButton11.setBounds(10, 251, 163, 37);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus No", "No of Seats", "Time of Leave", "Time of Arrive", "Bus Route No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 591, 270));

        jTabbedPane10.addTab("tab6", jPanel6);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Route No", "Start from", "City 1", "City 2", "City 3", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        jTabbedPane10.addTab("tab7", jPanel7);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Date of Birth", "Gender", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        jTabbedPane10.addTab("tab8", jPanel8);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Start from", "Destination", "Date", "Bus No", "Time", "Buyer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        jTabbedPane10.addTab("tab9", jPanel10);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Date of Birth", "Gender", "Phone Number", "Position", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        jScrollPane3.getAccessibleContext().setAccessibleName("tab1");

        jTabbedPane10.addTab("tab10", jPanel13);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Bus No", "Arrived At", "Left At"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        jTabbedPane10.addTab("tab6", jPanel15);

        jPanel14.add(jTabbedPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 0, 590, 290));
        jTabbedPane10.getAccessibleContext().setAccessibleName("tab3");
        jTabbedPane10.getAccessibleContext().setAccessibleDescription("");

        searchPanel.add(jPanel14);
        jPanel14.setBounds(180, 40, 616, 265);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/status.png"))); // NOI18N
        jButton1.setText("Status");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 51), null, null));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton1);
        jButton1.setBounds(10, 300, 160, 36);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N
        searchPanel.add(jLabel17);
        jLabel17.setBounds(0, -40, 800, 470);

        mainPanel.addTab("tab3", searchPanel);

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    mainPanel.setSelectedIndex(0);
             try
        {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system","root","1406");
                   
            String sql = "select Bus_BusNo from Bus";
            PreparedStatement pst = con.prepareStatement(sql);
           ResultSet rs = pst.executeQuery();//ResultSet is the return typed
           //above statement we will get all Busno from table class
           while(rs.next())
           {
               String Sbusno = rs.getString("Bus_BusNo");//here Bus_Busno is actual column name of the table
               busno.addItem(Sbusno);//add into jcomboBox
           }
           
           con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
          mainPanel.setSelectedIndex(1);//to navigate between the tab in tabbed pane
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         mainPanel.setSelectedIndex(4); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        dispose();
        MainScreen main = new  MainScreen();
        main.setLocationRelativeTo(null);
        main.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void passenger_phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_phonenoActionPerformed

    private void passenger_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passenger_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passenger_nameActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jTabbedPane10.setSelectedIndex(4);
        try
        {
            //open conncection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system", "root","1406");

            String sql = "Select User_name,User_dob,User_gender,User_phoneNo,User_position,User_address from User";
            PreparedStatement pstmt = con.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery(sql);
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));

            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane10.setSelectedIndex(3);
        try
        {
            //open conncection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system", "root","1406");

            String sql = "Select * from Booking";
            PreparedStatement pstmt = con.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery(sql);
            jTable5.setModel(DbUtils.resultSetToTableModel(rs));

            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane10.setSelectedIndex(2);

        try
        {
            //open conncection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system", "root","1406");
            //need to use user name and passwod at the end

            //    Statement st = con.createStatement();
            //mysql query
            String sql = "Select * from Passenger";
            PreparedStatement pstmt = con.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery(sql);
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

            //                while(rs.next())
            //                {
                //                    //data will be added until finish
                //                    String name = rs.getString("Passenger_name");//here  Passenger_name is coulumn name
                //                    String dob = rs.getString("Passenger_dob");
                //                    String  gender= rs.getString("Passenger_gender");
                //                    String phoneno = String.valueOf(rs.getInt("Passenger_phoneNo"));//convension due to int value
                //
                //                    //string array for stor data into jtable;
                //
                //                    String tbData[] = {name,dob,gender,phoneno};
                //                        DefaultTableMode1  tb1Mode1 = (DefaultTableMode1)jTable2.getModel();
                //
                //                        //add string array data into jTable
                //                        tb1Mode1.addRow(tbData);
                //                }

            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane10.setSelectedIndex(1);
        try
        {
            //open conncection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system", "root","1406");

            String sql = "Select * from Route";
            PreparedStatement pstmt = con.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery(sql);
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));

            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jTabbedPane10.setSelectedIndex(0);

        try
        {
            //open conncection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system", "root","1406");

            String sql = "Select * from Bus";
            PreparedStatement pstmt = con.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainPanel.setSelectedIndex(2);
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system","root","1406");
          
            //2nd combo box
           String sql = "select Route_city1 from Route";
            PreparedStatement pst = con.prepareStatement(sql);
           String combo_box;

           ResultSet rs2 = pst.executeQuery();//ResultSet is the return typed
           //above statement we will get all Busno from table class
            while(rs2.next())
           {
              combo_box = rs2.getString("Route_city1");//here Bus_Busno is actual column name of the table
              booking_to.addItem(combo_box);//add into jcomboBox
           } 
        
           sql = "select Route_city2 from Route";
           PreparedStatement pst11 = con.prepareStatement(sql);
           rs2 = pst11.executeQuery();
           while(rs2.next())
           {
              combo_box = rs2.getString("Route_city2");//here Bus_Busno is actual column name of the table
              booking_to.addItem(combo_box);//add into jcomboBox
           }
           
           sql = "select Route_city3 from Route";   
          PreparedStatement pst12 = con.prepareStatement(sql);
           rs2 = pst12.executeQuery();
           while(rs2.next())
           {
              combo_box = rs2.getString("Route_city3");//here Bus_Busno is actual column name of the table
              booking_to.addItem(combo_box);//add into jcomboBox
           }
                    
            sql = "select Route_To from Route";            
           PreparedStatement pst13 = con.prepareStatement(sql);
           rs2 = pst13.executeQuery();
           while(rs2.next())
           {
              combo_box = rs2.getString("Route_To");//here Bus_Busno is actual column name of the table
              booking_to.addItem(combo_box);//add into jcomboBox
           }
           
          
           //3rd combo box
            sql = "select Bus_BusNo from Bus";
           PreparedStatement pst3 = con.prepareStatement(sql);
           ResultSet rs3 = pst3.executeQuery();//ResultSet is the return typed
           //above statement we will get all Busno from table class
           while(rs3.next())
           {
              combo_box = rs3.getString("Bus_BusNo");//here Bus_Busno is actual column name of the table
              booking_busno.addItem(combo_box);//add into jcomboBox
           }
           
           
           //4rd combo box
           sql = "select Bus_TimeOfArrive from Bus";
           PreparedStatement pst4 = con.prepareStatement(sql);
           ResultSet rs4 = pst4.executeQuery();//ResultSet is the return typed
           //above statement we will get all Busno from table class
           
           while(rs4.next())
           {
              combo_box = rs4.getString("Bus_TimeOfArrive");//here Bus_Busno is actual column name of the table
              booking_time.addItem(combo_box);//add into jcomboBox
           }
           
           //5th combo box
           sql = "select Passenger_name from Passenger";
           PreparedStatement pst5 = con.prepareStatement(sql);
           ResultSet rs5 = pst5.executeQuery();//ResultSet is the return typed
           //above statement we will get all Busno from table class
           while(rs5.next())
           {
              combo_box = rs5.getString("Passenger_name");//here Bus_Busno is actual column name of the table
              booking_passenger.addItem(combo_box);//add into jcomboBox
           }
           
           
           
           
           
           con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainPanel.setSelectedIndex(3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane10.setSelectedIndex(5);        
                try
        {
            //open conncection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system", "root","1406");

            String sql = "select * from Status";
            PreparedStatement pstmt = con.prepareStatement(sql);

            ResultSet rs = pstmt.executeQuery(sql);
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));

            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system","root","1406");
         
            String sql = "insert into status values(?,?,?,?)";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            Object time11=  jSpinner1.getValue();
            Object time22=  jSpinner2.getValue();
             
            String sql1 = "select * from Bus";
            PreparedStatement pst = con.prepareStatement(sql1);
           ResultSet rs = pst.executeQuery();//ResultSet is the return typed
           
           while(rs.next())
           {
               String Sbusno = rs.getString("Bus_BusNo");
               busno.addItem(Sbusno);
           }
            
            
           String selectedbusno = null;
           selectedbusno = busno.getSelectedItem().toString();
            
            pstmt.setString(2,selectedbusno);  
            
                    if (time11 instanceof Date) {
                        Date date = (Date)time11;
                        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");//need to import the SinmpleDateFormat
                        String time1 = format.format(date);
                        pstmt.setString(3,time1);
                    }

                    if (time22 instanceof Date) {
                        Date date = (Date)time22;
                        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");//need to import the SinmpleDateFormat
                        String time2 = format.format(date);
                        pstmt.setString(4,time2);
                    }
            
 
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "isertion succesful");
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system","root","1406");
         
            String sql = "insert into passenger values(?,?,?,?)";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1,passenger_name.getText());
            pstmt.setString(2,((JTextField)passenger_dob.getDateEditor().getUiComponent()).getText());
            String dept = null;
            if(passenger_male.isSelected())
            {
                dept = passenger_male.getText();
            }
            if(passenger_female.isSelected())
            {
                dept = passenger_female.getText();
            }
            
            pstmt.setString(3,dept);
            pstmt.setInt(4,Integer.parseInt(passenger_phoneno.getText()));
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "isertion succesful");
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
          try{       
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_management_system","root","1406");
         
            String sql = "insert into booking values(?,?,?,?,?,?)";
            PreparedStatement pstmt = con.prepareStatement(sql);
            
           String selectedbooking = null;
           selectedbooking = booking_from.getSelectedItem().toString();
        
           String selectedbookedto = booking_to.getSelectedItem().toString();
           
           String selecteddate = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
           
           String selectedbusno = booking_busno.getSelectedItem().toString();
           
           String selectedtime = booking_time.getSelectedItem().toString();
           
           String selectedpassenger = booking_passenger.getSelectedItem().toString();
           
            pstmt.setString(1,selectedbooking); 
            pstmt.setString(2,selectedbookedto); 
            pstmt.setString(3,selecteddate); 
            pstmt.setString(4,selectedbusno); 
            pstmt.setString(5,selectedtime); 
            pstmt.setString(6,selectedpassenger);
            
            pstmt.executeUpdate();
           JOptionPane.showMessageDialog(null, "isertion succesful");   
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(null,e);
          }
    }//GEN-LAST:event_jButton9ActionPerformed
 
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        passenger_name.setText("");
        passenger_phoneno.setText("");//need to set up the clear for date and male female button

    }//GEN-LAST:event_jButton15ActionPerformed

    private void busnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busnoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_busnoActionPerformed

    private void booking_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booking_toActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookingMainPanel;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JComboBox<String> booking_busno;
    private javax.swing.JComboBox<String> booking_from;
    private javax.swing.JComboBox<String> booking_passenger;
    private javax.swing.JComboBox<String> booking_time;
    private javax.swing.JComboBox<String> booking_to;
    private javax.swing.JComboBox<String> busno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTabbedPane mainPanel;
    private javax.swing.JPanel passengerPanel;
    private com.toedter.calendar.JDateChooser passenger_dob;
    private javax.swing.JRadioButton passenger_female;
    private javax.swing.JRadioButton passenger_male;
    private javax.swing.JTextField passenger_name;
    private javax.swing.JTextField passenger_phoneno;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
}
